config/routes.rb
Rails.application.routes.draw do

  get 'information/top' => 'information#top'
  get 'blogs/index' => 'blogs#index'
  resources :blogs
  get 'blogs/:id' =>'blogs#show'
  post 'blogs/:id/destroy' => 'blogs/#destroy'

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/:id' =>"users#show"
  get 'information/top' => 'information#top'
  get '/' => 'home#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, {presence: true}
    validates :content, {presence: true}
    validates :user_id, {presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image, :prefecture])
        devise_parameter_sanitizer.permit(:account_update, keys:[:name,:image,:prefecture]) 
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find_by(id:params[:id])
  end

  def create
    @blog = Blog.new(blog_parameter)
    if @blog.save
      redirect_to blogs_path
    else
      render 'new'
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time, :migraine).merge(user_id: current_user.id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  def top
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :authenticate_user!
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  before_action :authenticate_user!, {only: [:edit,:update]}
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = User.find_by(id:params[:id])
    @migraine = Blog.where(migraine: "true").count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<div class="main text-center">
    
    <%= form_with(model: @blog, local: true) do |form| %>
        <h1 class="mb-5">投稿編集</h1>

        <div class="mb-5">
            <%= form.label :タイトル %>
            <%= form.text_field :title, class:"col-3"%>
        </div>

        <div class="content mb-5">
            <%= form.label :内容 %>
            <%= form.text_field :content , class:"col-3"%>
        </div>

        <div class="time mb-5">
            <%= form.label :時間 %>
            <%= form.datetime_select :start_time, class:"col-3"%>
        </div>

        <div class="list fs-3">
            <%= form.check_box :migraine, {} ,true,false %>
            <%= form.label :片頭痛 %>
        </div>

        <div class="submit">
            <%= form.submit "保存", class:"btn btn-secondary col-3 mt-3" %>
        </div>
    <% end %>
</div>

app/views/blogs/index.html.erb
<div class="main text-center">
    <h1>カレンダー</h1>
    <br>
<%= link_to '日記をかく', new_blog_path ,class:"btn btn-primary"%>
    <div class="container">
        <%= month_calendar events: @blogs do |date, blogs| %>
        <%= date.day%>
        <% blogs.each do |blog| %>
            <% if blog.user_id == current_user.id %>
                <div>
                    <% if blog.migraine == "true" %>
                        <%= link_to blog.title, blog ,class:"migraine text-decoration-none"%>
                    <% else %>
                        <%= link_to blog.title, blog ,class:"text-decoration-none"%>
                    <% end %>
                </div>
            <% end%>
        <% end %>
    </div>
<% end %>

app/views/blogs/new.html.erb
<div class="main text-center">
    <%= form_with(model: @blog, local: true) do |form| %>

        <h1 class="mb-5">
            今日の出来事を日記に書いてみましょう
        </h1>

        <div class="mb-5">
            <%= form.label :タイトル %>
            <%= form.text_field :title, class:"col-3"%>
        </div>

        <div class="content mb-5">
            <%= form.label :内容 %>
            <%= form.text_field :content , class:"col-3"%>
        </div>

        <div class="time mb-5">
            <%= form.label :時間 %>
            <%= form.datetime_select :start_time, class:"col-3 pl-5"%>
        </div>

        <div class="list">
            <%= form.check_box :migraine, {} , true, false %>
            <%= form.label :片頭痛%>
        </div>
    
        <div class="submit">
            <%= form.submit "作成", class:"btn btn-secondary col-3 mt-3" %>
        </div>
    <% end %>
</div>

app/views/blogs/show.html.erb
<div class="main text-center">
        <table class="blog-show">
            <tr class="pb-3">
                <td><strong>タイトル</strong></td>
                <td><%= @blog.title %><td>
            </tr>

            <tr class="pb-5">
                <td><strong>時間</strong></td>
                <td><%= @blog.start_time.strftime("%Y-%m-%d %H:%M") %></td>
            </tr>

            <tr class="pb-5">
                <td><strong>内容</strong></td>
                <td><%= @blog.content %></td>
            </tr>

            <tr>
                <td><strong>片頭痛</strong></td>
                <%if @blog.migraine == "true"%>
                    <td>あり</td>
                <% else %>
                    <td>なし</td>
                <% end %>
            </tr>
        </table>
        <%= link_to '編集', edit_blog_path(@blog) ,class:"btn btn-primary col-3 mt-3" %><br>
        <%= link_to '削除',blog_path(@blog.id),method: :delete ,class:"btn btn-success col-3 mt-3",data: { confirm: '投稿を削除しますか？' } %><br>
        <%= link_to '戻る', blogs_path, class:"btn btn-secondary col-3 mt-3"%>
</div>

app/views/home/top.html.erb
<div class="main text-center">
    <h1 class="mb-5 home">片頭痛会とは</h1>
    <h2 class="pb-5">自分の片頭痛の原因を見つけるアプリです。</h2>
    <h2>カレンダー機能や、日記をつけて頭痛の原因を見つけよう</h2>
</div>

app/views/information/top.html.erb
<h1 class="mb-5 pt-3 text-center">片頭痛予防に効果的な方法</h1>
    <div class="main text-left">
        <div class="top container">
            <h1 class="border-bottom pb-2 fst-italic mt-5">生活リズムを整える</h1>
            <p class="fs-3">・睡眠不足、寝すぎには注意</p>
        <div>
        <div class="container">
            <h1 class="border-bottom pb-2 fst-italic mt-5">規則正しい食生活</h1>
            <p class="fs-3">・空腹は片頭痛の引き金になります</p>
        <div>
        <div class="container">
            <h1 class="border-bottom pb-2 fst-italic mt-5">適度な運動</h1>
            <p class="fs-3">・軽い運動は血管の働きをよくします。夕方に40分くらい、週5日以上の歩行運動が理想的です。</p>
        <div>
        <div class="container">
            <h1 class="border-bottom pb-2 fst-italic mt-5">日差しを避ける</h1>
            <p class="fs-3">・日差しの多いところではサングラスをしましょう</p>
        <div>
        <div class="container">
            <h1 class="border-bottom pb-2 fst-italic mt-5">片頭痛に効果的な食品</h1>
            <p class="fs-3">
                ・ビタミンB2：   豚肉、卵、大豆、焼海苔、うなぎ、ごま<br>
                ・マグネシウム： ほうれん草、下記、大豆製品、魚介類<br>
                ・ビタミンC：    イチゴ、じゃがいも、緑茶<br>
                ・ビタミンE：    大豆、うなぎ、しじみ、落花生<br>
                ・ビタミンA：    バター、牛乳、卵黄、にんじん、ほうれん草<br>
                ・トリプトファン：牛乳、大豆、果実
            </p>
        <div>
    </div>
    <a href="https://www.shimoda-clinic.com/headache/prevention/">参考</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>片頭痛会</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>  
  </head>

  <body class="back">
    <ul class="head">
      <li><%= link_to("片頭痛会","/",class:"text-decoration-none")%></li>
      <li><%= link_to("片頭痛にならないために","/information/top",class:"text-decoration-none")%></li>
      <% if user_signed_in? %>
        <li><%= link_to(current_user.name,"/users/#{current_user.id}",class:"text-decoration-none")%></li>
        <li><%= link_to("ログアウト","/users/sign_out",class:"text-decoration-none",data: { confirm: 'ログアウトしますか？' })%></li>
        <li><%= link_to("カレンダー","/blogs/index",class:"text-decoration-none")%></li> 
        <li><%= link_to("日記","/blogs/new",class:"text-decoration-none")%></li>
      <% else %>
        <li><%= link_to("新規登録","/users/sign_up",class:"text-decoration-none")%></li>
        <li><%= link_to("ログイン","/users/sign_in",class:"text-decoration-none")%></li>
      <% end %>
    </ul>
    <script>
    $(function(){
        $('.main').fadeIn(2000);
    });
    </script>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading mb-3 fs-2">
    <%= link_to t('simple_calendar.previous',default: '先月'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '来月'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="weather text-right">
    <% if @user.image.present?%>
        <img src=<%= @user.image %> class = "icon_image">
    <% else%>
        <p class="icon-image_default"></p>
    <% end %>
    <br>
    <div class="container text-center">
        <p class="fs-3"><%=@user.name%></p>
        <%= link_to("ユーザ編集","/users/edit",class:"mt-3 btn btn-primary")%>
        <br>
        <%= link_to("カレンダー","/blogs/index",class:"mt-3 btn btn-secondary")%>
    </div>
</div>
<h1 class="prefecture"><%=@user.prefecture+"の天気"%></h1>
    <div id="weather">
        <script>
            $(function () {
                var API_KEY = '<%=ENV['OPEN_WEATHER_MAP_API']%>'; 
                var city = '<%=current_user.prefecture%>'; 
                var url = 'https://api.openweathermap.org/data/2.5/forecast?q=' + city + ',jp&units=metric&APPID=' + API_KEY;

                $.ajax({
                        url: url,
                        dataType: 'json',
                        type: 'GET',
                    })
                    .done(function (data) {
                        var insertHTML = '';
                        var cityName = data.city.name;
                        $('#city-name').html(cityName);
                
                        for (var i = 0; i <= 32; i = i + 8) {
                            insertHTML += buildHTML(data, i);
                        }
                    $('#weather').html(insertHTML);
                    })
                    .fail(function (data) {
                        alert('天気予報取得に失敗しました');
                });
            });
            
            
            function buildHTML(data, i) {
                var Week = new Array('(日)', '(月)', '(火)', '(水)', '(木)', '(金)', '(土)');
                var date = new Date(data.list[i].dt_txt);
                date.setHours(date.getHours() + 9);
                var month = date.getMonth() + 1;
                var day = month + '/' + date.getDate() + Week[date.getDay()];
                var icon = data.list[i].weather[0].icon;
                var html =
                    '<div class="weather-report">' +
                    '<img src="https://openweathermap.org/img/w/' + icon + '.png">' +
                    '<span class="weather-date">' + day + "</span>" +
                    '<div class="weather-temp-max">' + '最高：' + Math.round(data.list[i].main.temp_max) + "℃</div>" +
                    '<span class="weather-temp-min">' + '最低：' + Math.floor(data.list[i].main.temp_min) + "℃</span>" +
                    '</div>';
                return html
            }
        </script>
    </div>